### ISSUE TITLE
Buttons not working

### ISSUE THREAD

**Issue by wapfel20** [BlackrockDigital/startbootstrap-business-casual#20]
Hello,

I’ve ported this code base over to an S3 bucket and am building a custom form to leverage Lamda to send inquiries. Unfortunately, I cannot get any buttons on the website to function - both the mobile menu button and the contact form button seem to be non clickable.

The site is hosted at northtexasroofdoctors.com and the form is at northtexasroofdoctors.com/store.html. Just for reference, I have purposely forced the mobile menu to remain open since the button won’t function.

Thanks for your help and suggestions.

- Woody

**Comment by joeybab3** [comment]
Don't know if this is still an issue, but if you would still like help, your websites are not loading.

**Comment by davidtmiller** [comment]
Since this doesn't quite seem like a page issue and rather an implementation issue I'd suggest joining us on Slack and asking this question there: https://startbootstrap-slack.herokuapp.com/
