### ISSUE TITLE
Contact Form

### ISSUE THREAD

**Issue by allcool27** [BlackrockDigital/startbootstrap-business-casual#4]
Where do you find the "form" in the contact.html file. I am trying to sync my email with the contact form. I cannot find any file that I can enter a email into. please help

**Comment by davidtmiller** [comment]
The contact form in this template is just a design option and doesn't have any working mail feature attached to it. I may be changing this in the next version of the theme though.

**Comment by sysadminwatdo** [comment]
@allcool27 I'm working on a site with this, I was going to create a form handler for it in PHP - something to the effect of "send email and also drop form details into a db as a backup." Was going to use swiftmailer, which I believe offhand has a compatible license. Could gladly contribute it back if it would be useful to the larger project, @davidtmiller

**Comment by davidtmiller** [comment]
Feel free to submit a pull request @sysadminwatdo!
