### ISSUE TITLE
Update to Boostrap 4?

### ISSUE THREAD

**Issue by mccrodp** [BlackrockDigital/startbootstrap-business-casual#9]
Thanks for the template. I've been trying to [integrate it with an Elm front-end](https://github.com/ahimsayoga), using Elm's bootstrap packages to output the template. I'll make it more dynamic in future, but for the moment, just [trying to output the exact template](ahimsayoga.jp).

I've run into issue though as this is a Bootstrap 3 template, and Bootstrap 4 is latest, so some of the CSS in the new boostrap version takes precedence over this template's custom CSS and they styles aren't applied.

Any chance of a [Bootstrap 4](https://v4-alpha.getbootstrap.com/) update, is that on a roadmap? Thanks.

**Comment by davidtmiller** [comment]
Done with #11
